sources:
  - name: variables
    tables:
      - name: maquinas_rotativas
        description: "Tabela com o último status das máquinas"

models:
  - name: stg_bombas_raw
    description: "Camada staging das máquinas rotativas"
    config:
      schema: dbt
  - name: stg_maqRotativas_raw
    config:
      schema: dbt
  - name: stg_bombas_window
    config:
      schema: dbt
  - name: int_status
    config:
      schema: dbt
  - name: int_error
    config:
      schema: dbt
  - name: int_time
    config:
      schema: dbt